- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity # Frontier JobHeadOfSecurity<JobHeadOfSecurityOld
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-captain
  # canBeAntag: false
  ## Frontier: commented out stuff below
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025
  ## Frontier: commented out stuff above
  setPreference: true
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: HoSGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity # HL - Add departmental NF-style loadouts
    id: HoSPDA
#    gloves: ClothingHandsGlovesCombat # HL - Add departmental NF-style loadouts
    ears: ClothingHeadsetAltSecurity
    pocket1: NFWeaponPistolMk58 # Frontier: use NF version
  storage:
    back:
    - Flash
    - Magazine45_ACPPistolFMJ
