- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  # canBeAntag: false
  ## Frontier: commented out stuff below
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  # special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  ## End Frontier: commented out stuff above
  setPreference: true
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    id: SecurityPDA
#    eyes: ClothingEyesGlassesSecurity # HL - Add departmental NF-style loadouts
    ears: ClothingHeadsetSecurity
    pocket1: NFWeaponPistolMk58 # Frontier: use NF variant
  storage:
    back:
    - Flash
    - Magazine9x19mmPistolFMJ
