- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  # weight: 5 # Frontier
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  # canBeAntag: false
  ## Frontier: commented out stuff below
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  ## End Frontier: commented out stuff above
  setPreference: true
  accessGroups: # Frontier
  - GeneralAccess # Frontier

- type: startingGear
  id: WardenGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity # HL - Add departmental NF-style loadouts
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    pocket1: NFWeaponPistolMk58 # Frontier: use NF variant
  storage:
    back:
    - Flash
    - Magazine9x19mmPistolFMJ
