using Content.Shared.Traits;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._TE.Lobby.Ui.Roles;

[GenerateTypedNameReferences]
public sealed partial class TraitSelector : BoxContainer
{
    public event Action<bool>? PreferenceChanged;

    public bool Preference
    {
        get => ToggleableButton.Pressed;
        set => ToggleableButton.Pressed = value;
    }

    // Whether the selector should be locked. Used to prevent disabling the button while an invalid trait is selected (to allow it to be deselected)
    private bool _locked;

    public TraitSelector()
    {
        RobustXamlLoader.Load(this);

        ToggleableButton.OnToggled += OnButtonToggled;
    }

    public void Setup(TraitPrototype trait, FormattedMessage? requirementsMessage)
    {
        TitleLabel.Text = Loc.GetString(trait.Name);

        var costText = "";
        switch (trait.Cost)
        {
            case > 0:
                costText = $"-{trait.Cost}";
                CostLabel.FontColorOverride = Color.Red;
                break;
            case < 0:
                costText = $"+{-trait.Cost}";
                CostLabel.FontColorOverride = Color.Green;
                break;
            default:
                costText = $"{trait.Cost}";
                CostLabel.FontColorOverride = Color.Gray;
                break;
        }
        CostLabel.Text = costText;

        var tooltip = new Tooltip();
        var tooltipMessage = new FormattedMessage();

        if (trait.Description != null)
        {
            tooltipMessage = FormattedMessage.FromUnformatted(Loc.GetString(trait.Description));
        }

        if (requirementsMessage != null)
        {
            tooltipMessage.PushNewline();
            tooltipMessage.PushNewline();
            tooltipMessage.AddMessage(requirementsMessage);
        }

        tooltip.SetMessage(tooltipMessage);

        ToggleableButton.TooltipSupplier = _ => tooltip;
    }

    public void LockRequirements()
    {
        if (!Preference)
            ToggleableButton.Disabled = true;

        _locked = true;
    }

    public void UnlockRequirements()
    {
        ToggleableButton.Disabled = false;
        _locked = false;
    }

    private void OnButtonToggled(BaseButton.ButtonToggledEventArgs args)
    {
        PreferenceChanged?.Invoke(Preference);

        if (!Preference && _locked)
            LockRequirements();
    }

}

