- type: job # Move this to _HL later
  id: StationCaptain
  name: job-name-station-captain
  description: job-description-captain
  playTimeTracker: JobStationCaptain
  setPreference: true # Frontier
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - StationCaptain
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - Frontier
  accessGroups:
  - GeneralAccess # Frontier
  - AllAccess
  special:
  # - !type:AddImplantSpecial
  #   implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  ## Frontier: commented everything above out
